spring.application.name=springdemoe2e
spring.actuator.enabled=true
spring.datasource.url=jdbc:mysql://localhost:3306/radioheaven?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=password

# Enable exception handling for 404 errors
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param
server.error.include-exception=false

# To throw DispatcherServlet.NoHandlerFoundException when a mapping is not found
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

